
sudo rm -rf /System/Library/LaunchAgents/com.apple.applespell.plist
 /System/Library/LaunchAgents/com.apple.appstoreagent.plist
 /System/Library/LaunchAgents/com.apple.cloudd.plist
 /System/Library/LaunchAgents/com.apple.cloudpaird.plist
 /System/Library/LaunchAgents/com.apple.cloudphotod.plist
 /System/Library/LaunchAgents/com.apple.CoreLocationAgent.plist
 /System/Library/LaunchAgents/com.apple.findmymacmessenger.plist
 /System/Library/LaunchAgents/com.apple.homed.plist
 /System/Library/LaunchAgents/com.apple.icloud.findmydeviced.findmydevice-user-agent.plist
 /System/Library/LaunchAgents/com.apple.icloud.fmfd.plist
 /System/Library/LaunchAgents/com.apple.icloud.searchpartyuseragent.plist
 /System/Library/LaunchAgents/com.apple.iCloudUserNotifications.plist
 /System/Library/LaunchAgents/com.apple.photoanalysisd.plist
 /System/Library/LaunchAgents/com.apple.photolibraryd.plist
 /System/Library/LaunchAgents/com.apple.PhotoLibraryMigrationUtility.XPC.plist
 /System/Library/LaunchAgents/com.apple.RemoteDesktop.plist
 /System/Library/LaunchAgents/com.apple.RemoteManagementAgent.plist
 /System/Library/LaunchAgents/com.apple.screensharing.agent.plist
 /System/Library/LaunchAgents/com.apple.screensharing.MessagesAgent.plist
 /System/Library/LaunchAgents/com.apple.ScreenTimeAgent.plist
 /System/Library/LaunchAgents/com.apple.Siri.agent.plist
 /System/Library/LaunchAgents/com.apple.siriknowledged.plist
 /System/Library/LaunchAgents/com.apple.UsageTrackingAgent.plist
 /System/Library/LaunchAgents/com.openssh.ssh-agent.plist
 /System/Library/LaunchDaemons/com.apple.bluetoothd.plist
 /System/Library/LaunchDaemons/com.apple.findmymac.plist
 /System/Library/LaunchDaemons/com.apple.icloud.findmydeviced.plist
 /System/Library/LaunchDaemons/com.apple.icloud.searchpartyd.plist
 /System/Library/LaunchDaemons/com.apple.locate.plist
 /System/Library/LaunchDaemons/com.apple.locationd.plist
 /System/Library/LaunchDaemons/com.apple.RemoteDesktop.PrivilegeProxy.plist
 /System/Library/LaunchDaemons/com.apple.remotemanagementd.plist
 /System/Library/LaunchDaemons/com.apple.remotepairtool.plist
 /System/Library/LaunchDaemons/com.apple.screensharing.plist
 /System/Library/LaunchDaemons/ssh.plist
 /System/Library/LaunchAgents/com.apple.DiagnosticReportCleanup.plist.bak
 /System/Library/LaunchAgents/com.apple.DiagnosticReportCleanup.plist.bak
 /System/Library/LaunchAgents/com.apple.accessibility.AXVisualSupportAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.accessibility.dfrhud.plist.bak
 /System/Library/LaunchAgents/com.apple.accessibility.heard.plist.bak
 /System/Library/LaunchAgents/com.apple.AddressBook.abd.plist.bak
 /System/Library/LaunchAgents/com.apple.AddressBook.SourceSync.plist.bak
 /System/Library/LaunchAgents/com.apple.AirPlayUIAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.AirPortBaseStationAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.amp.mediasharingd.plist.bak
 /System/Library/LaunchAgents/com.apple.AOSHeartbeat.plist.bak
 /System/Library/LaunchAgents/com.apple.AOSPushRelay.plist.bak
 /System/Library/LaunchAgents/com.apple.ap.adprivacyd.plist.bak
 /System/Library/LaunchAgents/com.apple.ap.adservicesd.plist.bak
 /System/Library/LaunchAgents/com.apple.appleseed.seedusaged.plist.bak
 /System/Library/LaunchAgents/com.apple.appleseed.seedusaged.postinstall.plist.bak
 /System/Library/LaunchAgents/com.apple.assistant_service.plist.bak
 /System/Library/LaunchAgents/com.apple.assistantd.plist.bak
 /System/Library/LaunchAgents/com.apple.avconferenced.plist.bak
 /System/Library/LaunchAgents/com.apple.CalendarAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.CallHistoryPluginHelper.plist.bak
 /System/Library/LaunchAgents/com.apple.CallHistorySyncHelper.plist.bak
 /System/Library/LaunchAgents/com.apple.CommCenter-osx.plist.bak
 /System/Library/LaunchAgents/com.apple.DiagnosticReportCleanup.plist.bak
 /System/Library/LaunchAgents/com.apple.exchange.exchangesyncd.plist.bak
 /System/Library/LaunchAgents/com.apple.familycircled.plist.bak
 /System/Library/LaunchAgents/com.apple.familycontrols.useragent.plist.bak
 /System/Library/LaunchAgents/com.apple.familynotificationd.plist.bak
 /System/Library/LaunchAgents/com.apple.findmymacmessenger.plist.bak
 /System/Library/LaunchAgents/com.apple.followupd.plist.bak
 /System/Library/LaunchAgents/com.apple.gamed.plist.bak
 /System/Library/LaunchAgents/com.apple.helpd.plist.bak
 /System/Library/LaunchAgents/com.apple.homed.plist.bak
 /System/Library/LaunchAgents/com.apple.iCloudUserNotifications.plist.bak
 /System/Library/LaunchAgents/com.apple.identityservicesd.plist.bak
 /System/Library/LaunchAgents/com.apple.imagent.plist.bak
 /System/Library/LaunchAgents/com.apple.imautomatichistorydeletionagent.plist.bak
 /System/Library/LaunchAgents/com.apple.imklaunchagent.plist.bak
 /System/Library/LaunchAgents/com.apple.imtransferagent.plist.bak
 /System/Library/LaunchAgents/com.apple.java.InstallOnDemand.plist.bak
 /System/Library/LaunchAgents/com.apple.KeyboardAccessAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.keyboardservicesd.plist.bak
 /System/Library/LaunchAgents/com.apple.knowledge-agent.plist.bak
 /System/Library/LaunchAgents/com.apple.macos.studentd.plist.bak
 /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist.bak
 /System/Library/LaunchAgents/com.apple.mediaremoteagent.plist.bak
 /System/Library/LaunchAgents/com.apple.parentalcontrols.check.plist.bak
 /System/Library/LaunchAgents/com.apple.parsec-fbf.plist.bak
 /System/Library/LaunchAgents/com.apple.parsecd.plist.bak
 /System/Library/LaunchAgents/com.apple.passd.plist.bak
 /System/Library/LaunchAgents/com.apple.photoanalysisd.plist.bak
 /System/Library/LaunchAgents/com.apple.protectedcloudstorage.protectedcloudkeysyncing.plist.bak
 /System/Library/LaunchAgents/com.apple.quicklook.plist.bak
 /System/Library/LaunchAgents/com.apple.quicklook.ThumbnailsAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.quicklook.ui.helper.plist.bak
 /System/Library/LaunchAgents/com.apple.remindd.plist.bak
 /System/Library/LaunchAgents/com.apple.ReportCrash.plist.bak
 /System/Library/LaunchAgents/com.apple.ReportGPURestart.plist.bak
 /System/Library/LaunchAgents/com.apple.ReportPanic.plist.bak
 /System/Library/LaunchAgents/com.apple.screensharing.agent.plist.bak
 /System/Library/LaunchAgents/com.apple.screensharing.menuextra.plist.bak
 /System/Library/LaunchAgents/com.apple.screensharing.MessagesAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.ScreenTimeAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.security.cloudkeychainproxy3.plist.bak
 /System/Library/LaunchAgents/com.apple.security.keychain-circle-notification.plist.bak
 /System/Library/LaunchAgents/com.apple.sharingd.plist.bak
 /System/Library/LaunchAgents/com.apple.sidecar-hid-relay.plist.bak
 /System/Library/LaunchAgents/com.apple.sidecar-relay.plist.bak
 /System/Library/LaunchAgents/com.apple.Siri.agent.plist.bak
 /System/Library/LaunchAgents/com.apple.siriknowledged.plist.bak
 /System/Library/LaunchAgents/com.apple.SocialPushAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.spindump_agent.plist.bak
 /System/Library/LaunchAgents/com.apple.suggestd.plist.bak
 /System/Library/LaunchAgents/com.apple.syncdefaultsd.plist.bak
 /System/Library/LaunchAgents/com.apple.telephonyutilities.callservicesd.plist.bak
 /System/Library/LaunchAgents/com.apple.touristd.plist.bak
 /System/Library/LaunchAgents/com.apple.TrustEvaluationAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.UsageTrackingAgent.plist.bak
 /System/Library/LaunchAgents/com.apple.videosubscriptionsd.plist.bak
 /System/Library/LaunchAgents/com.apple.voicememod.plist.bak
 /System/Library/LaunchAgents/com.apple.VoiceOver.plist.bak
 /System/Library/LaunchAgents/com.apple.WebKit.PluginAgent.plist.bak
